### ISSUE TITLE
BK7231T e14 Bulb Pin Mapping

### ISSUE THREAD

**Issue by bonuzzz** [openshwprojects/OpenBK7231T_App#153]
I bought tuya e14 bulbs on aliexpress some time ago. I think there more noname than branded one.  I flashed them with your firmware and want to publish working pins:

pin6 pwm 4
pin7 pwm 3
pin8 pwm 5
pin24 pwm 2
pin26 pwm 1

![photo_2022-08-03 22 19 41](https://user-images.githubusercontent.com/6509127/183714670-ecd28870-8786-4802-83ed-312c35e90e8d.jpeg)
![photo_2022-08-03 22 19 46](https://user-images.githubusercontent.com/6509127/183714699-78a7491c-23eb-4fa0-b8c8-e28efccad7cb.jpeg)
![photo_2022-08-03 22 19 51](https://user-images.githubusercontent.com/6509127/183714714-2c4852c2-5390-484e-806e-fe37600885a9.jpeg)
![photo_2022-08-03 22 19 36](https://user-images.githubusercontent.com/6509127/183714731-1280978e-c5f2-426d-a812-ababbade23f7.jpeg)

**Comment by openshwprojects** [comment]
Thanks, but the better place for that would be the Teardowns section here:
https://www.elektroda.com/rtvforum/topic3911041.html
with an information where that bulb was bought and how was flashed

**Comment by bonuzzz** [comment]
@ardenking yes, I have

```
mqtt:
  light:
    - name: "Left Lamp1"
      state_topic: "left_lamp1/led_enableAll/get"
      command_topic: "cmnd/left_lamp1/led_enableAll"
      brightness_state_topic: "left_lamp1/led_dimmer/get"
      brightness_command_topic: "cmnd/left_lamp1/led_dimmer"
      rgb_state_topic: "left_lamp1/led_basecolor_rgb/get"
      rgb_command_topic: "cmnd/left_lamp1/led_basecolor_rgb"
      color_temp_command_topic: "cmnd/left_lamp1/led_temperature"
      color_temp_state_topic: "left_lamp1/led_temperature/get"
      rgb_command_template: "{{ '%02x%02x%02x' | format(red, green, blue)}}"
      rgb_value_template: "{{ value[0:2]|int(base=16) }},{{ value[2:4]|int(base=16) }},{{ value[4:6]|int(base=16) }}"
      qos: 0
      payload_on: "1"
      payload_off: "0"
      optimistic: false
      brightness_scale: 100
      brightness_value_template: "{{value}}"
```
