### ISSUE TITLE
Ability to send custom MQTT data

### ISSUE THREAD

**Issue by Wolfieeewolf** [openshwprojects/OpenBK7231T_App#927]
I would really like to see the ability to send custom MQTT data from OBK. At the moment, I have a few devices that send lots of data that I don't need showing up in Home Assistant. I know I can do it all manually inside of Home Assistant, but doing it that way makes for a very large configuration.yaml file that gets a little out of control to handle.

If OBK would allow me to send my own custom MQTT data instead of the auto-generated one, that would mean I only have to see the switches and sensors that I use.

For example, OBK sends out this script.

```
mqtt:
  switch:
  - unique_id: "Media_Switch_relay_1"
    name: 1
    state_topic: "obk6127C87F/1/get"
    command_topic: "obk6127C87F/1/set"
    qos: 1
    payload_on: 1
    payload_off: 0
    retain: true
    availability:
      - topic: "obk6127C87F/connected"
  - unique_id: "Media_Switch_relay_2"
    name: 2
    state_topic: "obk6127C87F/2/get"
    command_topic: "obk6127C87F/2/set"
    qos: 1
    payload_on: 1
    payload_off: 0
    retain: true
    availability:
      - topic: "obk6127C87F/connected"
  - unique_id: "Media_Switch_relay_3"
    name: 3
    state_topic: "obk6127C87F/3/get"
    command_topic: "obk6127C87F/3/set"
    qos: 1
    payload_on: 1
    payload_off: 0
    retain: true
    availability:
      - topic: "obk6127C87F/connected"
  - unique_id: "Media_Switch_relay_4"
    name: 4
    state_topic: "obk6127C87F/4/get"
    command_topic: "obk6127C87F/4/set"
    qos: 1
    payload_on: 1
    payload_off: 0
    retain: true
    availability:
      - topic: "obk6127C87F/connected"
```

I would like it to send something like this

```
mqtt: 

  light:
  ### Bedroom Light #####################
    - unique_id: bedswitch_relay_1
      name: "Bedroom Light"
      state_topic: "bedswitch/1/get"
      command_topic: "bedswitch/1/set"
      qos: 1
      payload_on: 1
      payload_off: 0
      retain: true
      availability:
      - topic: "bedswitch/connected"

  fan:
  ### Bedroom Fan ##########################
    - unique_id: "bedswitch_Channel_10"
      name: "Bedroom Fan"
      state_topic: "bedswitch/5/get"
      command_topic: "bedswitch/5/set"
      percentage_state_topic: "bedswitch/10/get"
      percentage_command_topic: "bedswitch/10/set"
      qos: 1
      payload_on: 1
      payload_off: 0
      speed_range_min: 1
      speed_range_max: 3
      retain: true
      availability:
        - topic: "bedswitch/connected"
```

This way it only exposes the switches I need and not the stuff I don't

I think this would be a great addition to the OBK firmware
